<img src="https://github.com/milena-seismo/DSB-Unit-03/blob/main/labs/02%20-%20Classification-LeftHanded/assets/ga-logo.png?raw=1" style="float: left; margin: 20px; height: 55px">

# Lab: Classification: Predicting Left-Handedness from Psychological Factors

---

One way to define the data science process is as follows:

1. Define the problem.
2. Obtain the data.
3. Explore the data.
4. Model the data.
5. Evaluate the model.
6. Answer the problem.

We'll walk through a full data science problem in this lab.

---
## Step 1: Define The Problem.

You're currently a data scientist working at a university. A professor of psychology is attempting to study the relationship between personalities and left-handedness. They have tasked you with gathering evidence so that they may publish.

As a data scientist, you know that any real data science problem must be **specific** and **conclusively answerable**. For example:
- Bad data science problem: "What is the link between obesity and blood pressure?"
    - This is vague and is not conclusively answerable. That is, two people might look at the conclusion and one may say "Sure, the problem has been answered!" and the other may say "The problem has not yet been answered."
- Good data science problem: "Does an association exist between obesity and blood pressure?"
    - This is more specific and is conclusively answerable. The problem specifically is asking for a "Yes" or "No" answer. Based on that, two independent people should both be able to say either "Yes, the problem has been answered" or "No, the problem has not yet been answered."
- Excellent data science problem: "As obesity increases, how does blood pressure change?"
    - This is very specific and is conclusively answerable. The problem specifically seeks to understand the effect of one variable on the other.

### In the context of the left-handedness and personality example, what are three specific and conclusively answerable problems that you could answer using data science?

> You might find it helpful to check out the codebook in the repo for some inspiration.

---
## Step 2: Obtain the data.

### Read in the file titled "data.csv":
> Hint: Despite being saved as a .csv file, you won't be able to simply `pd.read_csv()` this data!

In [9]:
# library imports
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/milena-seismo/DSB-Unit-03/refs/heads/main/labs/02%20-%20Classification-LeftHanded/data/data.csv", sep="\t")
df.head()

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,country,fromgoogle,engnat,age,education,gender,orientation,race,religion,hand
0,4,1,5,1,5,1,5,1,4,1,...,US,2,1,22,3,1,1,3,2,3
1,1,5,1,4,2,5,5,4,1,5,...,CA,2,1,14,1,2,2,6,1,1
2,1,2,1,1,5,4,3,2,1,4,...,NL,2,2,30,4,1,1,1,1,2
3,1,4,1,5,1,4,5,4,3,5,...,US,2,1,18,2,2,5,3,2,2
4,5,1,5,1,5,1,5,1,3,1,...,US,2,1,22,3,1,1,3,2,3

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4184 entries, 0 to 4183
Data columns (total 56 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Q1           4184 non-null   int64
 1   Q2           4184 non-null   int64
 2   Q3           4184 non-null   int64
 3   Q4           4184 non-null   int64
 4   Q5           4184 non-null   int64
 5   Q6           4184 non-null   int64
 6   Q7           4184 non-null   int64
 7   Q8           4184 non-null   int64
 8   Q9           4184 non-null   int64
 9   Q10          4184 non-null   int64
 10  Q11          4184 non-null   int64
 11  Q12          4184 non-null   int64
 12  Q13          4184 non-null   int64
 13  Q14          4184 non-null   int64
 14  Q15          4184 non-null   int64
 15  Q16          4184 non-null   int64
 16  Q17          4184 non-null   int64
 17  Q18          4184 non-null   int64
 18  Q19          4184 non-null   int64
 19  Q20          4184 non-null   int64
 20  Q21          4184 non-null   int64
 21  Q22          4184 non-null   int64
 22  Q23          4184 non-null   int64
 23  Q24          4184 non-null   int64
 24  Q25          4184 non-null   int64
 25  Q26          4184 non-null   int64
 26  Q27          4184 non-null   int64
 27  Q28          4184 non-null   int64
 28  Q29          4184 non-null   int64
 29  Q30          4184 non-null   int64
 30  Q31          4184 non-null   int64
 31  Q32          4184 non-null   int64
 32  Q33          4184 non-null   int64
 33  Q34          4184 non-null   int64
 34  Q35          4184 non-null   int64
 35  Q36          4184 non-null   int64
 36  Q37          4184 non-null   int64
 37  Q38          4184 non-null   int64
 38  Q39          4184 non-null   int64
 39  Q40          4184 non-null   int64
 40  Q41          4184 non-null   int64
 41  Q42          4184 non-null   int64
 42  Q43          4184 non-null   int64
 43  Q44          4184 non-null   int64
 44  introelapse  4184 non-null   int64
 45  testelapse   4184 non-null   int64
 46  country      4184 non-null   object
 47  fromgoogle   4184 non-null   int64
 48  engnat       4184 non-null   int64
 49  age          4184 non-null   int64
 50  education    4184 non-null   int64
 51  gender       4184 non-null   int64
 52  orientation  4184 non-null   int64
 53  race         4184 non-null   int64
 54  religion     4184 non-null   int64
 55  hand         4184 non-null   int64
dtypes: int64(55), object(1)
memory usage: 1.8+ MB

In [5]:
df.head()

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,country,fromgoogle,engnat,age,education,gender,orientation,race,religion,hand
0,4,1,5,1,5,1,5,1,4,1,...,US,2,1,22,3,1,1,3,2,3
1,1,5,1,4,2,5,5,4,1,5,...,CA,2,1,14,1,2,2,6,1,1
2,1,2,1,1,5,4,3,2,1,4,...,NL,2,2,30,4,1,1,1,1,2
3,1,4,1,5,1,4,5,4,3,5,...,US,2,1,18,2,2,5,3,2,2
4,5,1,5,1,5,1,5,1,3,1,...,US,2,1,22,3,1,1,3,2,3

In [6]:
df.isnull().sum()

Q1             0
Q2             0
Q3             0
Q4             0
Q5             0
Q6             0
Q7             0
Q8             0
Q9             0
Q10            0
Q11            0
Q12            0
Q13            0
Q14            0
Q15            0
Q16            0
Q17            0
Q18            0
Q19            0
Q20            0
Q21            0
Q22            0
Q23            0
Q24            0
Q25            0
Q26            0
Q27            0
Q28            0
Q29            0
Q30            0
Q31            0
Q32            0
Q33            0
Q34            0
Q35            0
Q36            0
Q37            0
Q38            0
Q39            0
Q40            0
Q41            0
Q42            0
Q43            0
Q44            0
introelapse    0
testelapse     0
country        0
fromgoogle     0
engnat         0
age            0
education      0
gender         0
orientation    0
race           0
religion       0
hand           0
dtype: int64

In [7]:
df["hand"].value_counts()

hand
1    3542
2     452
3     179
0      11
Name: count, dtype: int64

,Q1,Q2,Q3,Q4,Q5,Q6,Q7,Q8,Q9,Q10,...,country,fromgoogle,engnat,age,education,gender,orientation,race,religion,hand
0,4,1,5,1,5,1,5,1,4,1,...,US,2,1,22,3,1,1,3,2,3
1,1,5,1,4,2,5,5,4,1,5,...,CA,2,1,14,1,2,2,6,1,1
2,1,2,1,1,5,4,3,2,1,4,...,NL,2,2,30,4,1,1,1,1,2
3,1,4,1,5,1,4,5,4,3,5,...,US,2,1,18,2,2,5,3,2,2
4,5,1,5,1,5,1,5,1,3,1,...,US,2,1,22,3,1,1,3,2,3

---

## Step 3: Explore the data.

### Conduct background research:

Domain knowledge is irreplaceable. Figuring out what information is relevant to a problem, or what data would be useful to gather, is a major part of any end-to-end data science project! For this lab, you'll be using a dataset that someone else has put together, rather than collecting the data yourself.

Do some background research about personality and handedness. What features, if any, are likely to help you make good predictions? How well do you think you'll be able to model this? Write a few bullet points summarizing what you believe, and remember to cite external sources.

You don't have to be exhaustive here. Do enough research to form an opinion, and then move on.

> You'll be using the answers to Q1-Q44 for modeling; you can disregard other features, e.g. country, age, internet browser.

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4184 entries, 0 to 4183
Data columns (total 56 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Q1           4184 non-null   int64
 1   Q2           4184 non-null   int64
 2   Q3           4184 non-null   int64
 3   Q4           4184 non-null   int64
 4   Q5           4184 non-null   int64
 5   Q6           4184 non-null   int64
 6   Q7           4184 non-null   int64
 7   Q8           4184 non-null   int64
 8   Q9           4184 non-null   int64
 9   Q10          4184 non-null   int64
 10  Q11          4184 non-null   int64
 11  Q12          4184 non-null   int64
 12  Q13          4184 non-null   int64
 13  Q14          4184 non-null   int64
 14  Q15          4184 non-null   int64
 15  Q16          4184 non-null   int64
 16  Q17          4184 non-null   int64
 17  Q18          4184 non-null   int64
 18  Q19          4184 non-null   int64
 19  Q20          4184 non-null   int64
 20  Q21          4184 non-null   int64
 21  Q22          4184 non-null   int64
 22  Q23          4184 non-null   int64
 23  Q24          4184 non-null   int64
 24  Q25          4184 non-null   int64
 25  Q26          4184 non-null   int64
 26  Q27          4184 non-null   int64
 27  Q28          4184 non-null   int64
 28  Q29          4184 non-null   int64
 29  Q30          4184 non-null   int64
 30  Q31          4184 non-null   int64
 31  Q32          4184 non-null   int64
 32  Q33          4184 non-null   int64
 33  Q34          4184 non-null   int64
 34  Q35          4184 non-null   int64
 35  Q36          4184 non-null   int64
 36  Q37          4184 non-null   int64
 37  Q38          4184 non-null   int64
 38  Q39          4184 non-null   int64
 39  Q40          4184 non-null   int64
 40  Q41          4184 non-null   int64
 41  Q42          4184 non-null   int64
 42  Q43          4184 non-null   int64
 43  Q44          4184 non-null   int64
 44  introelapse  4184 non-null   int64
 45  testelapse   4184 non-null   int64
 46  country      4184 non-null   object
 47  fromgoogle   4184 non-null   int64
 48  engnat       4184 non-null   int64
 49  age          4184 non-null   int64
 50  education    4184 non-null   int64
 51  gender       4184 non-null   int64
 52  orientation  4184 non-null   int64
 53  race         4184 non-null   int64
 54  religion     4184 non-null   int64
 55  hand         4184 non-null   int64
dtypes: int64(55), object(1)
memory usage: 1.8+ MB

### Conduct exploratory data analysis on this dataset:

If you haven't already, be sure to check out the codebook in the repo, as that will help in your EDA process.

You might use this section to perform data cleaning if you find it to be necessary.

In [17]:
df["hand"].value_counts(normalize=True)

hand
1    0.848790
2    0.108315
3    0.042895
Name: proportion, dtype: float64

In [12]:
df = df.drop(df[df["hand"] == 0].index)

In [14]:
df["hand"].value_counts()

hand
1    3542
2     452
3     179
Name: count, dtype: int64

### Calculate and interpret the baseline accuracy rate:

In [15]:
baseline_accuracy = df["hand"].value_counts(normalize=True).max()

print("Baseline Accuracy:", baseline_accuracy)
print("Baseline Accuracy (%):", baseline_accuracy * 100)

Baseline Accuracy: 0.8487898394440451
Baseline Accuracy (%): 84.87898394440451

### Short answer questions:

In this lab you'll use K-nearest neighbors and logistic regression to model
handedness based off of psychological factors.

Answer the following related questions; your answers may be in bullet points
**on your own words**

#### Describe the difference between regression and classification problems:

In [ ]:
 Regression predicts a number (for example a house price).
-Classification predicts a category (for example left-handed or not).

#### Considering $k$-nearest neighbors, describe the relationship between $k$ and the bias-variance tradeoff:

In [ ]:
- Small k: the model follows the noise in the data. Low bias, high variance -overfitting.
- Large k: the model is very smooth. High bias, low variance - underfitting.

#### Why do we often standardize predictor variables when using $k$-nearest neighbors?

In [ ]:
- KNN uses distances between points
- A variable with big numbers, like income, would dominate a variable with small numbers (like age). Standardizing puts every variable on the same scale

#### Do you think we should standardize the explanatory variables for this problem? Why or why not?

In [ ]:
#Not really. Q1-Q44 are all answered on the same 1-5 scale, so no variable dominates the distance.

#### How do we settle on $k$ for a $k$-nearest neighbors model?

In [ ]:
Try several values of k and compare the accuracy on data the model has not seen (a test set or cross-validation).
Pick the k with the best score. An odd k avoids ties.

#### What is the default type of regularization for logistic regression as implemented in scikit-learn? (You might [check the documentation](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html).)

In [ ]:
#The default is L2 (Ridge) regularization, with C = 1.0.

#### [Bonus - Optional] Describe the relationship between the scikit-learn `LogisticRegression` argument `C` and regularization strength:

In [ ]:
#C is the inverse of regularization strength (C = 1/α). A smaller C means stronger regularization, while a larger C means weaker regularization.

#### Describe the relationship between regularization strength and the bias-variance tradeoff:

In [ ]:
# Stronger regularization shrinks the coefficients: higher bias, lower variance (less overfitting).
# Weaker regularization lets the coefficients grow: lower bias, higher variance (more overfitting).

#### Logistic regression is considered more interpretable than $k$-nearest neighbors. Explain why.

In [ ]:
#Logistic regression gives one coefficient per variable. The sign and size tell us how that variable changes the odds of the outcome.
#KNN has no coefficients. It only looks at the nearest neighbors, so it is hard to explain *why* it predicted something.

---

## Step 4 & 5 Modeling: $k$-nearest neighbors

### Train-test split your data:

Your explanatory variables should be all Q columns.

In [18]:
from sklearn.model_selection import train_test_split

X = df[[f"Q{i}" for i in range(1, 45)]]
y = df["hand"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)

### Create and fit four separate $k$-nearest neighbors models:

### Model 1: one with $k = 3$:

In [19]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

#### Model 2: one with $k = 5$

In [20]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

KNeighborsClassifier()

#### Model 3: one with $k = 15$

In [21]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=15)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=15)

#### Model 4: one with $k = 25$:

In [22]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=25)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=25)

### Evaluate your models:

Evaluate each of your four models on the training and testing sets, and
interpret the four scores.

Are any of your models overfit or underfit?

Do any of your models beat the baseline accuracy rate?

In [26]:
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd

results = []

for k in [5, 10, 15, 25]:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)

    results.append({
        "k": k,
        "Train Accuracy": knn.score(X_train, y_train),
        "Test Accuracy": knn.score(X_test, y_test)
    })

pd.DataFrame(results)

    k  Train Accuracy  Test Accuracy
0   5        0.853627       0.849617
1  10        0.848194       0.848659
2  15        0.848833       0.848659
3  25        0.848833       0.848659

In [27]:
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=25)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

print(classification_report(y_test, y_pred, zero_division=0))

              precision    recall  f1-score   support

           1       0.85      1.00      0.92       886
           2       0.00      0.00      0.00       113
           3       0.00      0.00      0.00        45

    accuracy                           0.85      1044
   macro avg       0.28      0.33      0.31      1044
weighted avg       0.72      0.85      0.78      1044

In [28]:
for k in [5, 10, 15, 25]:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_test)

    print(f"\nKNN with k={k}")
    print(classification_report(y_test, y_pred, zero_division=0))

KNN with k=5
              precision    recall  f1-score   support

           1       0.85      1.00      0.92       886
           2       0.56      0.04      0.08       113
           3       0.00      0.00      0.00        45

    accuracy                           0.85      1044
   macro avg       0.47      0.35      0.33      1044
weighted avg       0.78      0.85      0.79      1044


KNN with k=10
              precision    recall  f1-score   support

           1       0.85      1.00      0.92       886
           2       0.00      0.00      0.00       113
           3       0.00      0.00      0.00        45

    accuracy                           0.85      1044
   macro avg       0.28      0.33      0.31      1044
weighted avg       0.72      0.85      0.78      1044


KNN with k=15
              precision    recall  f1-score   support

           1       0.85      1.00      0.92       886
           2       0.00      0.00      0.00       113
           3       0.00      0.00      0.00        45

    accuracy                           0.85      1044
   macro avg       0.28      0.33      0.31      1044
weighted avg       0.72      0.85      0.78      1044


KNN with k=25
              precision    recall  f1-score   support

           1       0.85      1.00      0.92       886
           2       0.00      0.00      0.00       113
           3       0.00      0.00      0.00        45

    accuracy                           0.85      1044
   macro avg       0.28      0.33      0.31      1044
weighted avg       0.72      0.85      0.78      1044

In [ ]:
#**Evaluation of KNN Models**

All four KNN models achieved approximately 85% test accuracy, which is similar to the baseline accuracy of 84.9%.

The model with k=5 performed slightly better at identifying left-handed individuals, with a recall of 4%. The other models (k=10, 15, and 25) failed to identify any left-handed individuals.

The dataset is highly imbalanced, with right-handed individuals representing the majority. Therefore, high accuracy does not necessarily indicate good classification performance.

**Conclusion:** None of the four KNN models is effective for predicting left-handedness. The k=5 model identifies a small number of left-handed individuals, but its recall is still very low.

---

## Step 4 & 5 Modeling: logistic regression

### Create and fit four separate logistic regression models:

*(Hint: Be careful with how you specify $\alpha$ in your model!)*
Note: You can use the same train and test data as above.

#### Model 1 : one with LASSO and $\alpha = 1$

#### Model 2 : one with LASSO and $\alpha = 10$

#### Model 3 : one with RIDGE and $\alpha = 1$

#### Model 4 : one with RIDGE and $\alpha = 10$

### Evaluate your models:

Evaluate each of your four models on the training and testing sets, and
interpret the four scores.

Are any of your models overfit or underfit?

Do any of your models beat the baseline accuracy rate?

---

## Step 6: Answer the problem.

Are any of your models worth moving forward with? What are the "best" models?